### ISSUE TITLE
Practica 3_Operaciones con sistemas numericos_A1S_Lennin Gomez Sanchez.

### ISSUE THREAD

**Issue by LenninGS-0** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-LenninGS-0#1]
[Actividad 3_Lennin Gomez Sanchez_A1S_Matematicas Discretas.pdf](https://github.com/user-attachments/files/16841430/Actividad.3_Lennin.Gomez.Sanchez_A1S_Matematicas.Discretas.pdf)

**Comment by YulianaMorales18** [comment]
portada 25/25
procedimiento 25/25
figuras ilustrativas y fotografías 25/25
resultados y conclusiones 25/25

final 100/100

**Comment by josealfredo79** [comment]
bien hecho y  revisado..
